# This is a basic workflow to help you get started with Actions

name: Release Binary

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - windows-latest
        - ubuntu-latest
        - macos-latest
        - macos-15-intel
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12.4
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - run: |
        poetry install --no-root
        poetry build
        poetry run pip install --no-index --find-links=dist nutcracker
        mv dist dist_old
        poetry run pyinstaller --onefile -n nutcracker src/nutcracker/runner.py
    # Optionally verify that it works (provided that it does not need user interaction)
    - run: ./dist/nutcracker --help
    - run: cp README.md ./dist/README.md
    - run: poetry run pip-licenses --from=all --format=plain-vertical --with-license-file --no-license-path --with-urls --with-description --output-file ./dist/LICENSE

    - uses: actions/upload-artifact@v4
      with:
        name: nutcracker-${{ runner.os }}_${{ runner.arch }}
        path: dist/*
